#
# 	This script reads the .root files generated by ReadingTreeMC, and checks
#	the histograms for NaN bins, and sets them to 0. This is done instead of
#	skipping entire plots.
#
###############################################################################

from ROOT import *
import math

bins = [0, 50, 100, 150, 200, 300, 400, 500, 600, 800, 1000, 1200, 1500]
vars = ["pt","c1","bdt","ntrk","eta","width"]

finput1 = TFile.Open("trijet-sherpa-py.root")
foutput1 = TFile("trijet_sherpa_clean.root","recreate")

for i in bins:
	for var in vars:
		bin = str(i)

		print(i,var)

		if i >= 400:
			q1 = finput1.Get(bin+"_j1_Forward_Quark_"+var)
			g1 = finput1.Get(bin+"_j1_Forward_Gluon_"+var)
			o1 = finput1.Get(bin+"_j1_Forward_Other_"+var)
			for k in range(1,q1.GetNbinsX()+1):
				a = q1.GetBinContent(k)
				b = g1.GetBinContent(k)
				c = o1.GetBinContent(k)
				if math.isnan(a) == True : q1.SetBinContent(k,0)
				if math.isnan(b) == True : g1.SetBinContent(k,0)
				if math.isnan(c) == True : o1.SetBinContent(k,0)
			q1.Write()
			g1.Write()
			o1.Write()

		q2 = finput1.Get(bin+"_j2_Forward_Quark_"+var)
		g2 = finput1.Get(bin+"_j2_Forward_Gluon_"+var)
		o2 = finput1.Get(bin+"_j2_Forward_Other_"+var)
		for k in range(1,q2.GetNbinsX()+1):
			d = q2.GetBinContent(k)
			e = g2.GetBinContent(k)
			f = o2.GetBinContent(k)
			if math.isnan(d) == True : q2.SetBinContent(k,0)
			if math.isnan(e) == True : g2.SetBinContent(k,0)
			if math.isnan(f) == True : o2.SetBinContent(k,0)
		q2.Write()
		g2.Write()
		o2.Write()

		if i < 1000:
			q3 = finput1.Get(bin+"_j3_Forward_Quark_"+var)
			g3 = finput1.Get(bin+"_j3_Forward_Gluon_"+var)
			o3 = finput1.Get(bin+"_j3_Forward_Other_"+var)
			for k in range(1,q3.GetNbinsX()+1):
				g = q3.GetBinContent(k)
				h = g3.GetBinContent(k)
				l = o3.GetBinContent(k)
				if math.isnan(g) == True : q3.SetBinContent(k,0)
				if math.isnan(h) == True : g3.SetBinContent(k,0)
				if math.isnan(l) == True : o3.SetBinContent(k,0)
			q3.Write()
			g3.Write()
			o3.Write()

foutput1.Write()
foutput1.Close()
